#!/usr/bin/env bash
# Build the PaideiaOS kernel.
#
# Invokes paideia-as on every .pdx file under src/kernel/, links the
# resulting objects via src/kernel/link.ld, produces build/kernel.elf.

set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
PAIDEIA_AS="$("${REPO_ROOT}/tools/find-paideia-as.sh")"
BUILD_DIR="${REPO_ROOT}/build"
KERNEL_SRC="${REPO_ROOT}/src/kernel"
LINK_SCRIPT="${KERNEL_SRC}/link.ld"

if [[ ! -f "${LINK_SCRIPT}" ]]; then
    echo "linker script missing: ${LINK_SCRIPT}" >&2
    exit 1
fi

mkdir -p "${BUILD_DIR}"

echo "[build-user] ensuring build/user/shell.bin (R15-M1-007 embed prerequisite)"
"${REPO_ROOT}/tools/build-user.sh"

echo "[boot-stub] tools/boot_stub.S -> boot_stub.o (32+64-bit, as --64)"
BOOT_STUB_OBJ="${BUILD_DIR}/boot_stub.o"
as --64 -o "${BOOT_STUB_OBJ}" "${REPO_ROOT}/tools/boot_stub.S"

echo "[userbin] tools/userbin_embed.S -> userbin_embed.o"
USERBIN_OBJ="${BUILD_DIR}/userbin_embed.o"
( cd "${REPO_ROOT}" && as --64 -o "${USERBIN_OBJ}" tools/userbin_embed.S )

# R18-M1-002 (#761): AP boot trampoline. Standalone-link the trampoline
# blob to VMA=0x8000, extract flat bytes via objcopy, then .incbin the
# result into kernel .rodata via tools/ap_trampoline_embed.S. See
# tools/ap_trampoline.S / tools/ap_trampoline.ld for the trampoline
# proper.
echo "[ap-tramp] tools/ap_trampoline.S -> ap_trampoline.bin (real->prot->long)"
AP_TRAMP_OBJ="${BUILD_DIR}/ap_trampoline.o"
AP_TRAMP_ELF="${BUILD_DIR}/ap_trampoline.elf"
AP_TRAMP_BIN="${BUILD_DIR}/ap_trampoline.bin"
as --64 -o "${AP_TRAMP_OBJ}" "${REPO_ROOT}/tools/ap_trampoline.S"
ld -T "${REPO_ROOT}/tools/ap_trampoline.ld" -o "${AP_TRAMP_ELF}" "${AP_TRAMP_OBJ}"
objcopy -O binary "${AP_TRAMP_ELF}" "${AP_TRAMP_BIN}"

echo "[ap-tramp-embed] tools/ap_trampoline_embed.S -> ap_trampoline_embed.o"
AP_TRAMP_EMBED_OBJ="${BUILD_DIR}/ap_trampoline_embed.o"
( cd "${REPO_ROOT}" && as --64 -o "${AP_TRAMP_EMBED_OBJ}" tools/ap_trampoline_embed.S )

# #761: propagate the trampoline's parameter-slot byte offsets from the
# standalone-linked ap_trampoline.elf into kernel.elf as absolute
# symbols. Reads the `_ap_trampoline_{pml4,stack,entry}_offset` values
# from the standalone .set directives via nm and re-emits them via
# `.set` into a generated ap_trampoline_offsets.o. Future issues
# (#762/#763) patching the slots load these constants as immediates.
AP_TRAMP_OFF_SRC="${BUILD_DIR}/ap_trampoline_offsets.S"
AP_TRAMP_OFF_OBJ="${BUILD_DIR}/ap_trampoline_offsets.o"
PML4_OFF=$(nm --defined-only "${AP_TRAMP_ELF}" \
             | awk '$3 == "_ap_trampoline_pml4_offset"  {print $1; exit}')
STACK_OFF=$(nm --defined-only "${AP_TRAMP_ELF}" \
             | awk '$3 == "_ap_trampoline_stack_offset" {print $1; exit}')
ENTRY_OFF=$(nm --defined-only "${AP_TRAMP_ELF}" \
             | awk '$3 == "_ap_trampoline_entry_offset" {print $1; exit}')
if [[ -z "${PML4_OFF}" || -z "${STACK_OFF}" || -z "${ENTRY_OFF}" ]]; then
    echo "[ap-tramp] FAIL: could not locate _ap_trampoline_*_offset symbols in ${AP_TRAMP_ELF}" >&2
    exit 1
fi
cat > "${AP_TRAMP_OFF_SRC}" <<EOF
# Auto-generated by tools/build.sh from build/ap_trampoline.elf .set symbols.
# DO NOT EDIT. See tools/ap_trampoline.S for the source of truth.
.global _ap_trampoline_pml4_offset
.set    _ap_trampoline_pml4_offset,  0x${PML4_OFF}
.global _ap_trampoline_stack_offset
.set    _ap_trampoline_stack_offset, 0x${STACK_OFF}
.global _ap_trampoline_entry_offset
.set    _ap_trampoline_entry_offset, 0x${ENTRY_OFF}
EOF
as --64 -o "${AP_TRAMP_OFF_OBJ}" "${AP_TRAMP_OFF_SRC}"

OBJECTS=()
while IFS= read -r -d '' pdx; do
    rel="${pdx#"${KERNEL_SRC}"/}"
    obj="${BUILD_DIR}/${rel%.pdx}.o"
    mkdir -p "$(dirname "${obj}")"
    echo "[build] paideia-as ${rel} -> ${obj#"${BUILD_DIR}"/}"
    "${PAIDEIA_AS}" build --emit elf64 "${pdx}" -o "${obj}"
    OBJECTS+=("${obj}")
done < <(find "${KERNEL_SRC}" -name '*.pdx' -not -path '*/boot_panic/*' -not -path '*/boot_exc3/*' -print0 | sort -z)

OBJECTS=( "${BOOT_STUB_OBJ}" "${USERBIN_OBJ}" "${AP_TRAMP_EMBED_OBJ}" "${AP_TRAMP_OFF_OBJ}" "${OBJECTS[@]}" )

if [[ ${#OBJECTS[@]} -eq 0 ]]; then
    echo "no .pdx files found under ${KERNEL_SRC}" >&2
    exit 1
fi

# Symbol export now provides uart_init/uart_puts definitions
# tools/stubs.S is no longer needed for linking
# echo "[stub] tools/stubs.S — Phase-7-in-progress link stubs"
# STUBS_OBJ="${BUILD_DIR}/stubs.o"
# as --64 -o "${STUBS_OBJ}" "${REPO_ROOT}/tools/stubs.S"
# OBJECTS+=("${STUBS_OBJ}")

echo "[link] ld -T link.ld -> kernel.elf"
# paideia-as 0.6.0 doesn't yet emit top-level let-fn bindings as named ELF
# symbols (the encoder ships them as a synthetic `add_one` placeholder), so
# inter-file references like `call uart_init` show up as undefined PLT32
# relocations at link time. tools/stubs.S provides empty `ret` bodies for
# each placeholder symbol; ld resolves the PLT32 relocs against them. The
# kernel returns through these stubs at runtime (no UART, no init) but the
# image links and QEMU can load it. Real symbol-export lands in a later
# paideia-as phase.
ld -nostdlib --warn-common --fatal-warnings -T "${LINK_SCRIPT}" -o "${BUILD_DIR}/kernel.elf" "${OBJECTS[@]}"

echo "[audit] R_X86_64_32 relocations must not target high-VA (>= 0xffff800000000000) symbols"

NM_MAP="${BUILD_DIR}/.nm.map"
SEC_MAP="${BUILD_DIR}/.sec.map"

nm build/kernel.elf | awk 'NF>=3 {print $3, $1}' > "${NM_MAP}"
readelf -SW build/kernel.elf \
    | awk '$2 ~ /^[0-9]+\]$/ && $3 != "NULL" {print $3, $5}' > "${SEC_MAP}"

AUDIT_FAIL=0
for obj in "${OBJECTS[@]}"; do
    while IFS= read -r target; do
        [[ -z "${target}" ]] && continue
        if [[ "${target}" == .* ]]; then
            vma=$(awk -v s="${target}" '$1==s {print $2; exit}' "${SEC_MAP}")
        else
            vma=$(awk -v s="${target}" '$1==s {print $2; exit}' "${NM_MAP}")
        fi
        [[ -z "${vma}" ]] && continue
        if [[ "${vma}" == ffff8* ]]; then
            echo "[audit] FAIL: ${obj#"${BUILD_DIR}"/}: R_X86_64_32 -> ${target} @ 0x${vma}" >&2
            AUDIT_FAIL=1
        fi
    done < <(readelf -r "${obj}" 2>/dev/null \
             | awk '$3 == "R_X86_64_32" || $3 == "R_X86_64_32S" {print $5}' \
             | sort -u)
done

if [[ ${AUDIT_FAIL} -ne 0 ]]; then
    echo "[audit] R_X86_64_32 high-VA audit failed — see #490 census, #494 policy" >&2
    exit 1
fi
echo "[audit] R_X86_64_32 relocations clean (all targets low-VA)"

echo "[verify] kernel syscall dispatch alignment"
"${REPO_ROOT}/tools/verify-syscall-dispatch.sh" "${BUILD_DIR}/kernel.elf" || {
    echo "[FAIL] syscall dispatch verification failed" >&2
    exit 1
}

echo "[verify] sched_block/sched_wake precondition guards (#663)"
"${REPO_ROOT}/tools/verify-sched-guards.sh" "${BUILD_DIR}/kernel.elf" || {
    echo "[FAIL] sched guards verification failed" >&2
    exit 1
}

echo "[verify] tty_read blocking wrapper real body (#667)"
"${REPO_ROOT}/tools/verify-tty-read-wrapper.sh" || {
    echo "[FAIL] tty_read wrapper verification failed" >&2
    exit 1
}

echo "[ok] ${BUILD_DIR}/kernel.elf"
