#!/usr/bin/env bash
# Build the PaideiaOS kernel.
#
# Invokes paideia-as on every .pdx file under src/kernel/, links the
# resulting objects via src/kernel/link.ld, produces build/kernel.elf.

set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
PAIDEIA_AS="$("${REPO_ROOT}/tools/find-paideia-as.sh")"
BUILD_DIR="${REPO_ROOT}/build"
KERNEL_SRC="${REPO_ROOT}/src/kernel"
LINK_SCRIPT="${KERNEL_SRC}/link.ld"

if [[ ! -f "${LINK_SCRIPT}" ]]; then
    echo "linker script missing: ${LINK_SCRIPT}" >&2
    exit 1
fi

mkdir -p "${BUILD_DIR}"

# R20-M4-004 (#822): "No AML in kernel" guardrail. Refuses the build
# if any AML-related identifier (aml*, dsdt, ssdt, acpica, \_SB_) has
# leaked into src/kernel/**. See design/acpi/no-aml-in-kernel.md for
# the full forbidden set and rationale. Runs first so a violation is
# reported before any (slower) assembler work.
echo "[no-aml-lint] tools/lint-no-kernel-aml.sh"
"${REPO_ROOT}/tools/lint-no-kernel-aml.sh" || {
    echo "[FAIL] no-AML kernel guardrail tripped (#822)" >&2
    exit 1
}

echo "[build-user] ensuring build/user/shell.bin (R15-M1-007 embed prerequisite)"
"${REPO_ROOT}/tools/build-user.sh"

echo "[boot-stub] tools/boot_stub.S -> boot_stub.o (32+64-bit, as --64)"
BOOT_STUB_OBJ="${BUILD_DIR}/boot_stub.o"
as --64 -o "${BOOT_STUB_OBJ}" "${REPO_ROOT}/tools/boot_stub.S"

echo "[userbin] tools/userbin_embed.S -> userbin_embed.o"
USERBIN_OBJ="${BUILD_DIR}/userbin_embed.o"
( cd "${REPO_ROOT}" && as --64 -o "${USERBIN_OBJ}" tools/userbin_embed.S )

# R18-M1-002 (#761): AP boot trampoline. Standalone-link the trampoline
# blob to VMA=0x8000, extract flat bytes via objcopy, then .incbin the
# result into kernel .rodata via tools/ap_trampoline_embed.S. See
# tools/ap_trampoline.S / tools/ap_trampoline.ld for the trampoline
# proper.
echo "[ap-tramp] tools/ap_trampoline.S -> ap_trampoline.bin (real->prot->long)"
AP_TRAMP_OBJ="${BUILD_DIR}/ap_trampoline.o"
AP_TRAMP_ELF="${BUILD_DIR}/ap_trampoline.elf"
AP_TRAMP_BIN="${BUILD_DIR}/ap_trampoline.bin"
as --64 -o "${AP_TRAMP_OBJ}" "${REPO_ROOT}/tools/ap_trampoline.S"
ld -T "${REPO_ROOT}/tools/ap_trampoline.ld" -o "${AP_TRAMP_ELF}" "${AP_TRAMP_OBJ}"
objcopy -O binary "${AP_TRAMP_ELF}" "${AP_TRAMP_BIN}"

echo "[ap-tramp-embed] tools/ap_trampoline_embed.S -> ap_trampoline_embed.o"
AP_TRAMP_EMBED_OBJ="${BUILD_DIR}/ap_trampoline_embed.o"
( cd "${REPO_ROOT}" && as --64 -o "${AP_TRAMP_EMBED_OBJ}" tools/ap_trampoline_embed.S )

# #761: propagate the trampoline's parameter-slot byte offsets from the
# standalone-linked ap_trampoline.elf into kernel.elf as absolute
# symbols. Reads the `_ap_trampoline_{pml4,stack,entry}_offset` values
# from the standalone .set directives via nm and re-emits them via
# `.set` into a generated ap_trampoline_offsets.o. Future issues
# (#762/#763) patching the slots load these constants as immediates.
AP_TRAMP_OFF_SRC="${BUILD_DIR}/ap_trampoline_offsets.S"
AP_TRAMP_OFF_OBJ="${BUILD_DIR}/ap_trampoline_offsets.o"
PML4_OFF=$(nm --defined-only "${AP_TRAMP_ELF}" \
             | awk '$3 == "_ap_trampoline_pml4_offset"  {print $1; exit}')
STACK_OFF=$(nm --defined-only "${AP_TRAMP_ELF}" \
             | awk '$3 == "_ap_trampoline_stack_offset" {print $1; exit}')
ENTRY_OFF=$(nm --defined-only "${AP_TRAMP_ELF}" \
             | awk '$3 == "_ap_trampoline_entry_offset" {print $1; exit}')
if [[ -z "${PML4_OFF}" || -z "${STACK_OFF}" || -z "${ENTRY_OFF}" ]]; then
    echo "[ap-tramp] FAIL: could not locate _ap_trampoline_*_offset symbols in ${AP_TRAMP_ELF}" >&2
    exit 1
fi
cat > "${AP_TRAMP_OFF_SRC}" <<EOF
# Auto-generated by tools/build.sh from build/ap_trampoline.elf .set symbols.
# DO NOT EDIT. See tools/ap_trampoline.S for the source of truth.
.global _ap_trampoline_pml4_offset
.set    _ap_trampoline_pml4_offset,  0x${PML4_OFF}
.global _ap_trampoline_stack_offset
.set    _ap_trampoline_stack_offset, 0x${STACK_OFF}
.global _ap_trampoline_entry_offset
.set    _ap_trampoline_entry_offset, 0x${ENTRY_OFF}
EOF
as --64 -o "${AP_TRAMP_OFF_OBJ}" "${AP_TRAMP_OFF_SRC}"

OBJECTS=()
while IFS= read -r -d '' pdx; do
    rel="${pdx#"${KERNEL_SRC}"/}"
    obj="${BUILD_DIR}/${rel%.pdx}.o"
    mkdir -p "$(dirname "${obj}")"
    echo "[build] paideia-as ${rel} -> ${obj#"${BUILD_DIR}"/}"
    "${PAIDEIA_AS}" build --emit elf64 "${pdx}" -o "${obj}"
    OBJECTS+=("${obj}")
done < <(find "${KERNEL_SRC}" -name '*.pdx' -not -path '*/boot_panic/*' -not -path '*/boot_exc3/*' -print0 | sort -z)

# R18-M5-004 (#778): compile any .pdx fixtures under tests/kernel/ into
# kernel objects too. These live outside src/kernel/ so they do not
# pollute the primary source tree, but they need to be linked into
# kernel.elf so their `pub` witness functions (e.g. tlb_shootdown_witness)
# are callable from bring-up wire-ups. Object paths are namespaced under
# build/tests/kernel/ to keep the build tree unambiguous.
TESTS_KERNEL_DIR="${REPO_ROOT}/tests/kernel"
if [[ -d "${TESTS_KERNEL_DIR}" ]]; then
    while IFS= read -r -d '' pdx; do
        rel="${pdx#"${REPO_ROOT}"/}"
        obj="${BUILD_DIR}/${rel%.pdx}.o"
        mkdir -p "$(dirname "${obj}")"
        echo "[build] paideia-as ${rel} -> ${obj#"${BUILD_DIR}"/}"
        "${PAIDEIA_AS}" build --emit elf64 "${pdx}" -o "${obj}"
        OBJECTS+=("${obj}")
    done < <(find "${TESTS_KERNEL_DIR}" -name '*.pdx' \
        -not -path '*/drivers/elaborator/*' \
        -print0 | sort -z)
fi

# R29-M2-002 (#1024): elaborator negatives under tests/kernel/drivers/
# elaborator/ are INTENTIONALLY REJECTED by paideia-as. They must never
# be swept into the kernel build — verified separately via
# tools/verify-elaborator-negatives.sh, wired into .githooks/pre-push
# as the `elaborator-negatives` step. The `-not -path` filter above
# excludes the whole directory; verification lives in the negatives
# script rather than the object-emitting build path.

# R30.M3-001 (#1061): OP-REGION ROW-TABLE CONFINEMENT.
#
# _op_region_table is the only place in the kernel where a {address
# space, base, length} triple lives, and the entire security argument of
# R30.M3 is that its ONLY writer — opregion_tail_alloc — is reachable
# solely through two gates: the root mint, which demands the base-kind
# capability the space requires, and the derive path, which containment-
# checks the request against the parent window and refuses rather than
# clipping.
#
# That argument is a claim about ONE FILE until it is checked. `objdump
# -r` is the only way to check it mechanically: a kernel object that
# relocates against the table is an object that can write a row without
# passing either gate. A future issue that "just pokes the base in" for
# an EC or LPSS window, or a debug helper that fixes up a length, would
# void the guarantee with no symptom until a firmware table reached an
# address nobody granted it. The build fails here instead.
#
# The check is in build.sh rather than in the pre-push hook deliberately:
# it then runs on every build, including inside the smoke matrix, rather
# than only at push time.
OPREG_OWNER="${BUILD_DIR}/core/cap/kind_op_region.o"
if [[ ! -f "${OPREG_OWNER}" ]]; then
    echo "[opregion-confine] FAIL: ${OPREG_OWNER} not built" >&2
    exit 1
fi
if ! objdump -r "${OPREG_OWNER}" 2>/dev/null | grep -qE '_op_region_table([^a-zA-Z0-9_]|$)'; then
    echo "[opregion-confine] FAIL: kind_op_region.o does not reference _op_region_table" >&2
    echo "  The symbol was renamed or the module was gutted; the confinement" >&2
    echo "  check would then pass vacuously, so it fails instead." >&2
    exit 1
fi
opreg_strays=""
for o in "${OBJECTS[@]}"; do
    [[ "${o}" == "${OPREG_OWNER}" ]] && continue
    if objdump -r "${o}" 2>/dev/null | grep -qE '_op_region_table([^a-zA-Z0-9_]|$)'; then
        opreg_strays="${opreg_strays} ${o#"${BUILD_DIR}"/}"
    fi
done
if [[ -n "${opreg_strays}" ]]; then
    echo "[opregion-confine] FAIL — objects other than kind_op_region.o relocate" >&2
    echo "  against _op_region_table:${opreg_strays}" >&2
    echo "  Only opregion_tail_alloc may write a region row, and only behind the" >&2
    echo "  root-mint and derive gates. See src/kernel/core/cap/kind_op_region.pdx." >&2
    exit 1
fi
echo "[opregion-confine] _op_region_table confined to core/cap/kind_op_region.o"

# R30.M4-001 (#1066) / R30.M4-002 (#1067): SCI/GPE PATH GUARDRAILS.
#
# Three checks, in increasing order of what they buy.
#
# (1) STORAGE CONFINEMENT, the same shape as the OP-REGION check above.
#     _gpe_cfg holds the validated block geometry, _gpe_dispatch_table
#     and _gpe_event_ring hold the registration rows and the queued
#     events, and _gpe_io_mode selects between real port I/O and the
#     synthetic window. Each has exactly one legitimate writing module,
#     and an object outside it that relocates against one of these is
#     an object that can install an unvalidated geometry, register a
#     subscriber without a range check, forge an event, or leave the
#     kernel addressing RAM in place of the platform's GPE block.
#
# (2) PORT-I/O CONFINEMENT. `in`/`out` carry no effect-row or
#     capability coupling in paideia-as yet (paideia-as#1312), so the
#     elaborator cannot refuse a stray port access the way it refuses
#     an uncapability'd MMIO effect. Until it can, "every GPE register
#     access goes through gpe_io_read8 / gpe_io_write8" is enforced
#     here: core/acpi/gpe_io.o is the only object under core/acpi/ that
#     may contain the IN/OUT opcodes at all.
#
# (3) ISR CALL-TARGET ALLOWLIST — the important one. A GPE's meaning is
#     a firmware control method; those are bytecode, the interpreter is
#     a userspace process, and evaluating one can block for
#     milliseconds. "The ISR does not evaluate one" has to be a
#     property of the call graph rather than of anyone's intent, so the
#     set of symbols core/acpi/sci_isr.o references is required to be a
#     SUBSET of the list below. Every entry is a bounded, non-blocking
#     leaf or near-leaf, which makes this simultaneously the no-
#     evaluation guarantee and the boundedness guarantee: adding a call
#     to an interpreter entry point, an IPC send, a scheduler yield, a
#     lock or an allocator fails the build by name.
GPE_CONFINE_OK=1
gpe_confine_one() {
    # $1 = symbol, $2 = owning object path (relative to BUILD_DIR)
    local sym="$1" owner="${BUILD_DIR}/$2" strays=""
    if [[ ! -f "${owner}" ]]; then
        echo "[gpe-confine] FAIL: ${owner} not built" >&2
        GPE_CONFINE_OK=0
        return
    fi
    if ! objdump -r "${owner}" 2>/dev/null | grep -qE "${sym}([^a-zA-Z0-9_]|\$)"; then
        echo "[gpe-confine] FAIL: $2 does not reference ${sym}" >&2
        echo "  The symbol was renamed or the module was gutted; the confinement" >&2
        echo "  check would then pass vacuously, so it fails instead." >&2
        GPE_CONFINE_OK=0
        return
    fi
    for o in "${OBJECTS[@]}"; do
        [[ "${o}" == "${owner}" ]] && continue
        if objdump -r "${o}" 2>/dev/null | grep -qE "${sym}([^a-zA-Z0-9_]|\$)"; then
            strays="${strays} ${o#"${BUILD_DIR}"/}"
        fi
    done
    if [[ -n "${strays}" ]]; then
        echo "[gpe-confine] FAIL — objects other than $2 relocate against ${sym}:${strays}" >&2
        GPE_CONFINE_OK=0
    fi
}
gpe_confine_one '_gpe_cfg'            'core/acpi/gpe_block.o'
gpe_confine_one '_gpe_dispatch_table' 'core/acpi/gpe_table.o'
gpe_confine_one '_gpe_event_ring'     'core/acpi/gpe_table.o'
gpe_confine_one '_gpe_io_mode'        'core/acpi/gpe_io.o'
gpe_confine_one '_gpe_io_synth_ram'   'core/acpi/gpe_io.o'
if [[ "${GPE_CONFINE_OK}" -ne 1 ]]; then
    echo "  See src/kernel/core/acpi/gpe_block.pdx and gpe_table.pdx for why each" >&2
    echo "  of these has exactly one legitimate writer." >&2
    exit 1
fi
echo "[gpe-confine] GPE geometry, dispatch table, event ring and I/O seam confined"

# (2) Port I/O confinement under core/acpi/.
gpe_io_strays=""
for o in "${OBJECTS[@]}"; do
    case "${o}" in
        "${BUILD_DIR}"/core/acpi/*) ;;
        *) continue ;;
    esac
    [[ "${o}" == "${BUILD_DIR}/core/acpi/gpe_io.o" ]] && continue
    # IN AL,DX = 0xEC ; IN EAX,DX = 0xED ; OUT DX,AL = 0xEE ; OUT DX,EAX = 0xEF
    if objdump -d "${o}" 2>/dev/null | grep -qE '^\s+[0-9a-f]+:.*\b(in|out)\s+(\(%dx\),%(al|ax|eax)|%(al|ax|eax),\(%dx\))'; then
        gpe_io_strays="${gpe_io_strays} ${o#"${BUILD_DIR}"/}"
    fi
done
if [[ -n "${gpe_io_strays}" ]]; then
    echo "[gpe-portio] FAIL — port I/O outside core/acpi/gpe_io.o:${gpe_io_strays}" >&2
    echo "  Every GPE register access must go through gpe_io_read8 / gpe_io_write8." >&2
    echo "  paideia-as#1312 will make this an effect-row property; until then it is" >&2
    echo "  this check. See src/kernel/core/acpi/gpe_io.pdx." >&2
    exit 1
fi
echo "[gpe-portio] port I/O under core/acpi/ confined to gpe_io.o"

# (3) ISR call-target allowlist.
SCI_ISR_OBJ="${BUILD_DIR}/core/acpi/sci_isr.o"
if [[ ! -f "${SCI_ISR_OBJ}" ]]; then
    echo "[sci-isr-allowlist] FAIL: ${SCI_ISR_OBJ} not built" >&2
    exit 1
fi
SCI_ISR_ALLOWED="
gpe_block_reg_bytes
gpe_block_status_base
gpe_block_enable_base
gpe_block_index_base
gpe_io_read8
gpe_io_write8
gpe_io_eoi
gpe_lookup
gpe_note_strike
gpe_mark_perm_masked
gpe_mark_pending
gpe_event_enqueue
drv_audit_emit
"
sci_isr_refs=$(objdump -r "${SCI_ISR_OBJ}" 2>/dev/null \
    | awk 'NF >= 3 && $1 ~ /^[0-9a-f]+$/ { print $3 }' \
    | sed -e 's/[-+]0x[0-9a-f]*$//' | sort -u)
if [[ -z "${sci_isr_refs}" ]]; then
    echo "[sci-isr-allowlist] FAIL: no relocations found in sci_isr.o" >&2
    echo "  The ISR was gutted or inlined away; the allowlist would then pass" >&2
    echo "  vacuously, so it fails instead." >&2
    exit 1
fi
sci_isr_bad=""
while IFS= read -r sym; do
    [[ -z "${sym}" ]] && continue
    if ! printf '%s\n' ${SCI_ISR_ALLOWED} | grep -qx -- "${sym}"; then
        sci_isr_bad="${sci_isr_bad} ${sym}"
    fi
done <<< "${sci_isr_refs}"
if [[ -n "${sci_isr_bad}" ]]; then
    echo "[sci-isr-allowlist] FAIL — core/acpi/sci_isr.o references:${sci_isr_bad}" >&2
    echo "  The SCI ISR may only call bounded, non-blocking primitives. No firmware" >&2
    echo "  method evaluation, no IPC, no scheduling, no allocation, no locks." >&2
    echo "  If a new call really belongs in interrupt context, add it to" >&2
    echo "  SCI_ISR_ALLOWED here AND say in the commit why it is bounded." >&2
    echo "  See src/kernel/core/acpi/sci_isr.pdx §The allowlist." >&2
    exit 1
fi
echo "[sci-isr-allowlist] sci_isr.o call targets within the bounded allowlist"

OBJECTS=( "${BOOT_STUB_OBJ}" "${USERBIN_OBJ}" "${AP_TRAMP_EMBED_OBJ}" "${AP_TRAMP_OFF_OBJ}" "${OBJECTS[@]}" )

if [[ ${#OBJECTS[@]} -eq 0 ]]; then
    echo "no .pdx files found under ${KERNEL_SRC}" >&2
    exit 1
fi

# Symbol export now provides uart_init/uart_puts definitions
# tools/stubs.S is no longer needed for linking
# echo "[stub] tools/stubs.S — Phase-7-in-progress link stubs"
# STUBS_OBJ="${BUILD_DIR}/stubs.o"
# as --64 -o "${STUBS_OBJ}" "${REPO_ROOT}/tools/stubs.S"
# OBJECTS+=("${STUBS_OBJ}")

echo "[link] ld -T link.ld -> kernel.elf"
# paideia-as 0.6.0 doesn't yet emit top-level let-fn bindings as named ELF
# symbols (the encoder ships them as a synthetic `add_one` placeholder), so
# inter-file references like `call uart_init` show up as undefined PLT32
# relocations at link time. tools/stubs.S provides empty `ret` bodies for
# each placeholder symbol; ld resolves the PLT32 relocs against them. The
# kernel returns through these stubs at runtime (no UART, no init) but the
# image links and QEMU can load it. Real symbol-export lands in a later
# paideia-as phase.
ld -nostdlib --warn-common --fatal-warnings -T "${LINK_SCRIPT}" -o "${BUILD_DIR}/kernel.elf" "${OBJECTS[@]}"

echo "[audit] R_X86_64_32 relocations must not target high-VA (>= 0xffff800000000000) symbols"

NM_MAP="${BUILD_DIR}/.nm.map"
SEC_MAP="${BUILD_DIR}/.sec.map"

nm build/kernel.elf | awk 'NF>=3 {print $3, $1}' > "${NM_MAP}"
readelf -SW build/kernel.elf \
    | awk '$2 ~ /^[0-9]+\]$/ && $3 != "NULL" {print $3, $5}' > "${SEC_MAP}"

AUDIT_FAIL=0
for obj in "${OBJECTS[@]}"; do
    while IFS= read -r target; do
        [[ -z "${target}" ]] && continue
        if [[ "${target}" == .* ]]; then
            vma=$(awk -v s="${target}" '$1==s {print $2; exit}' "${SEC_MAP}")
        else
            vma=$(awk -v s="${target}" '$1==s {print $2; exit}' "${NM_MAP}")
        fi
        [[ -z "${vma}" ]] && continue
        if [[ "${vma}" == ffff8* ]]; then
            echo "[audit] FAIL: ${obj#"${BUILD_DIR}"/}: R_X86_64_32 -> ${target} @ 0x${vma}" >&2
            AUDIT_FAIL=1
        fi
    done < <(readelf -r "${obj}" 2>/dev/null \
             | awk '$3 == "R_X86_64_32" || $3 == "R_X86_64_32S" {print $5}' \
             | sort -u)
done

if [[ ${AUDIT_FAIL} -ne 0 ]]; then
    echo "[audit] R_X86_64_32 high-VA audit failed — see #490 census, #494 policy" >&2
    exit 1
fi
echo "[audit] R_X86_64_32 relocations clean (all targets low-VA)"

echo "[verify] kernel syscall dispatch alignment"
"${REPO_ROOT}/tools/verify-syscall-dispatch.sh" "${BUILD_DIR}/kernel.elf" || {
    echo "[FAIL] syscall dispatch verification failed" >&2
    exit 1
}

echo "[verify] sched_block/sched_wake precondition guards (#663)"
"${REPO_ROOT}/tools/verify-sched-guards.sh" "${BUILD_DIR}/kernel.elf" || {
    echo "[FAIL] sched guards verification failed" >&2
    exit 1
}

echo "[verify] tty_read blocking wrapper real body (#667)"
"${REPO_ROOT}/tools/verify-tty-read-wrapper.sh" || {
    echo "[FAIL] tty_read wrapper verification failed" >&2
    exit 1
}

echo "[ok] ${BUILD_DIR}/kernel.elf"
