#!/bin/bash
# tools/gen-file-ids.sh — M6-001 (#696) file_ids constant generator
#
# Walks src/kernel/**/*.pdx (sorted) and emits:
#   1. FILE_ID_module_name constants for each file (ordinal index)
#   2. _klog_files [u64; N] rodata array of name-string pointers
#
# Usage: tools/gen-file-ids.sh > src/kernel/core/klog/file_ids.pdx
#
# Idempotent: byte-identical output on re-run. Sorted paths ensure stable ordering.
# Not wired into build yet (manual invocation during M8 Makefile integration).

set -e

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

# Find all .pdx files in src/kernel, sorted by path (stable across systems)
readarray -t KERNEL_FILES < <(find src/kernel -name "*.pdx" -type f | LC_ALL=C sort)
FILE_COUNT=${#KERNEL_FILES[@]}

# Generate header
cat << 'EOF'
// src/kernel/core/klog/file_ids.pdx — M6-001 (#696) file identification constants
//
// Auto-generated by tools/gen-file-ids.sh. DO NOT EDIT MANUALLY.
// Contains FILE_ID_* constants (one per kernel .pdx) and _klog_files[] rodata array.
//
// Each constant identifies a source file by ordinal:
//   FILE_ID_kernel_main = 0
//   FILE_ID_klog_panic = 1
//   ... (all kernel .pdx files in sorted path order)
//
// The _klog_files array maps ordinals back to name-string pointers for
// reverse lookup during panic dump (future: higher-level name rendering).
//
// Audit: paideia-os#696 (two-phase witness plan)

module FileIds = structure {

EOF

# Emit FILE_ID_* constants and name strings
for IDX in "${!KERNEL_FILES[@]}"; do
  FILE="${KERNEL_FILES[$IDX]}"
  # Extract relative path and convert to snake_case symbol name
  RELPATH="${FILE#src/kernel/}"
  RELPATH="${RELPATH%.pdx}"
  # Convert path separators + hyphens to underscores (identifier-safe)
  SYMBOL_NAME=$(echo "$RELPATH" | sed -e 's|/|_|g' -e 's|-|_|g')
  # Compute string length (path + NUL terminator)
  STR_LEN=$((${#RELPATH} + 1))

  echo "  pub let FILE_ID_${SYMBOL_NAME} : u64 = ${IDX}"
  echo "  pub let name_file_${IDX} : [u8; ${STR_LEN}] = \"${RELPATH}\\0\""
  echo ""
done

# Emit the _klog_files array
echo "  pub let _klog_files : [u64; ${FILE_COUNT}] = ["
for IDX in "${!KERNEL_FILES[@]}"; do
  if [ $((IDX + 1)) -lt $FILE_COUNT ]; then
    echo "    (rip + name_file_${IDX}),"
  else
    echo "    (rip + name_file_${IDX})"
  fi
done

cat << 'EOF'
  ]
}
EOF
