#!/usr/bin/env bash
# tools/verify-file-id-hardcodes.sh — #1605 file-id hardcode drift gate
#
# WHAT THIS POLICES
#
# src/kernel/core/klog/file_ids.pdx is regenerated by tools/gen-file-ids.sh
# and its FILE_ID_* ordinals CHANGE whenever a .pdx is added, removed, or
# renamed under src/kernel/ (the ordinals come from LC_ALL=C sort of the
# path list). Call sites that pass a FILE_ID to kassert_fail have two
# faithful shapes:
#
#   (a) mov rsi, FILE_ID_core_fs_vfs_open;    // symbolic
#   (b) mov rsi, 464; // FILE_ID_core_fs_vfs_open
#
# Shape (a) resolves through the linker and cannot drift.
# Shape (b) is a numeric literal PAIRED with a FILE_ID_* comment naming
# the intended constant. That pair is a drift trap: a rename or an added
# file shifts every ordinal from that path onward, but the literal keeps
# passing assembly. #1605 documented five such pairs whose ordinals had
# drifted from the file_ids.pdx table by hundreds of positions -- silent
# because kassert_fail happily accepts any u64 as a file id and the
# panic-time dump uses it as an index into _klog_files, so a wrong id
# just names the WRONG FILE in the fault report.
#
# This gate refuses that. For every literal-plus-FILE_ID_comment pair it
# finds in src/kernel/**, it reads the current file_ids.pdx, resolves
# the named FILE_ID_ constant to its ordinal, and asserts the numeric
# literal matches. Any mismatch fails the build.
#
# The gate ALSO catches a rename-without-touching-the-callsite: if a
# call site names FILE_ID_XYZ in the comment but no such symbol exists
# in file_ids.pdx (e.g. a file rename removed it), the lookup fails and
# the build refuses -- the caller has to be updated.
#
# Symbolic sites are preferred and are NOT policed by this gate; they
# cannot drift by construction. The gate exists for the residual literal
# form, which is a legitimate style choice for hot paths where the
# assembler prefers a real immediate over a linker relocation, and for
# code being converted incrementally.
#
# Exit 0: no drift.
# Exit 1: at least one hardcoded ordinal does not match file_ids.pdx.

set -uo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
KERNEL_SRC="${REPO_ROOT}/src/kernel"
FILE_IDS="${KERNEL_SRC}/core/klog/file_ids.pdx"
TAG="[file-id-hardcodes]"

if [[ ! -f "${FILE_IDS}" ]]; then
    echo "${TAG} FAIL: ${FILE_IDS} not found — run tools/gen-file-ids.sh" >&2
    exit 1
fi

# Regex captures three fields:
#   1) any register name after `mov ` up to `,`
#   2) a decimal literal
#   3) the FILE_ID_* symbol named in the trailing comment
#
# The comment MUST live on the same line as the mov, and the FILE_ID_
# name is the drift-target identifier. If someone writes a plain literal
# without a FILE_ID_ comment, this gate cannot tell what it was meant to
# be -- and that is fine, because the drift trap is specifically the
# pattern where the LITERAL AND THE INTENDED SYMBOL are both present and
# ONE is a lie. A bare literal is somebody else's problem.
LITERAL_RE='mov[[:space:]]+[a-z][a-z0-9]+[[:space:]]*,[[:space:]]*([0-9]+)[[:space:]]*;.*(FILE_ID_[A-Za-z0-9_]+)'

fail=0
scanned=0
matched=0

while IFS= read -r -d '' path; do
    # Skip the generated file itself: it declares the constants, it does
    # not consume them.
    [[ "${path}" == "${FILE_IDS}" ]] && continue

    while IFS= read -r line; do
        # bash regex on the line; capture literal and symbol
        if [[ "${line}" =~ ${LITERAL_RE} ]]; then
            literal="${BASH_REMATCH[1]}"
            symbol="${BASH_REMATCH[2]}"
            matched=$((matched + 1))

            # Look up the ordinal for this symbol in file_ids.pdx.
            # The declaration shape is exactly:
            #   pub let FILE_ID_<symbol> : u64 = <ordinal>
            # Anchored so a substring-name cannot false-match.
            ordinal=$(grep -E "^[[:space:]]*pub[[:space:]]+let[[:space:]]+${symbol}[[:space:]]*:" \
                            "${FILE_IDS}" \
                       | head -1 \
                       | sed -E 's/.*=[[:space:]]*([0-9]+).*/\1/')

            if [[ -z "${ordinal}" ]]; then
                rel="${path#${REPO_ROOT}/}"
                echo "${TAG} FAIL: ${rel} references ${symbol} but no such symbol in file_ids.pdx" >&2
                echo "${TAG}         line: ${line}" >&2
                fail=1
                continue
            fi

            if [[ "${literal}" != "${ordinal}" ]]; then
                rel="${path#${REPO_ROOT}/}"
                echo "${TAG} DRIFT: ${rel} — literal ${literal}, ${symbol} is now ${ordinal}" >&2
                echo "${TAG}         line: ${line}" >&2
                fail=1
            fi
        fi
    done < "${path}"
    scanned=$((scanned + 1))
done < <(find "${KERNEL_SRC}" -type f -name '*.pdx' -print0)

if [[ ${fail} -ne 0 ]]; then
    echo "" >&2
    echo "${TAG} At least one file-id literal disagrees with the current" >&2
    echo "${TAG} src/kernel/core/klog/file_ids.pdx table. Either:" >&2
    echo "${TAG}   (a) update the numeric literal to match the ordinal above, or" >&2
    echo "${TAG}   (b) preferred: change the site to the symbolic form" >&2
    echo "${TAG}         mov rsi, ${symbol}  // symbolic; drift-proof" >&2
    echo "${TAG} #1605 landed the preferred form for the five sites this" >&2
    echo "${TAG} gate was designed to catch." >&2
    exit 1
fi

echo "${TAG} scanned ${scanned} kernel .pdx files, ${matched} literal-plus-FILE_ID_ pairs, all match"
exit 0
